[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"
clap =  { version = "4.0", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.17.11"
log = "0.4.25"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"

